name: dartdoku
description: A sample command-line application.
version: 1.0.4
homepage: https://hello.rusondia.net

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
 args: ^2.0.0
 pedantic: ^1.11.0

dev_dependencies:
  test: ^1.14.4
