name: dartdoku
description: A sample command-line application.
version: 1.0.3
homepage: https://hello.rusondia.net

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
 args: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
